version: "3"
services:
    poke-api:
      build:
        context: .
        dockerfile: resources/docker/Dockerfile
      restart: on-failure
      ports:
      - "3030:3030"
      environment:
        RUST_LOG: "info"
